### ISSUE TITLE
Could not find suitable distribution for pytest-runner

### ISSUE THREAD

**Issue by Axieum** [Kozea/cairocffi#180] opened 2021-01-22 06:14 UTC
Please find below log of Pip attempting to collect `carocffi==1.2.0` from an internally hosted PyPi repository, there is no public access to https://pypi.org. This is also in production while trying to install `weasyprint`, for some reason it depends on `pytest-runner`?

```
Collecting cairocffi==1.2.0
--
  | Downloading https://[redacted]/artifactory/api/pypi/pypi/packages/packages/84/ca/0bffed5116d21251469df200448667e90acaa5131edea869b44a3fbc73d0/cairocffi-1.2.0.tar.gz  (70kB)
  | ERROR: Command errored out with exit status 1:
  | command: /opt/app-root/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j50vi2ji/cairocffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j50vi2ji/cairocffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-j50vi2ji/cairocffi/pip-egg-info
  | cwd: /tmp/pip-install-j50vi2ji/cairocffi/
  | Complete output (25 lines):
  | Download error on https://pypi.org/simple/pytest-runner/:  [Errno -2] Name or service not known -- Some packages may not be found!
  | Couldn't find index page for 'pytest-runner' (maybe misspelled?)
  | Download error on https://pypi.org/simple/:  [Errno -2] Name or service not known -- Some packages may not be found!
  | No local packages or working download links found for pytest-runner
  | Traceback (most recent call last):
  | File "<string>", line 1, in <module>
  | File "/tmp/pip-install-j50vi2ji/cairocffi/setup.py", line 10, in <module>
  | setup(
  | File "/opt/app-root/lib64/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
  | _install_setup_requires(attrs)
  | File "/opt/app-root/lib64/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
  | dist.fetch_build_eggs(dist.setup_requires)
  | File "/opt/app-root/lib64/python3.8/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
  | resolved_dists = pkg_resources.working_set.resolve(
  | File "/opt/app-root/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
  | dist = best[req.key] = env.best_match(
  | File "/opt/app-root/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
  | return self.obtain(req, installer)
  | File "/opt/app-root/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
  | return installer(requirement)
  | File "/opt/app-root/lib64/python3.8/site-packages/setuptools/dist.py", line 787, in fetch_build_egg
  | return cmd.easy_install(req)
  | File "/opt/app-root/lib64/python3.8/site-packages/setuptools/command/easy_install.py", line 678, in easy_install
  | raise DistutilsError(msg)
  | distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
  | ----------------------------------------
```

**Comment by liZe** [comment] 2021-01-22 11:01
Hello!

Your issue is actually a duplicate of #157. You can manually install `pytest-runner` as a workaround, until we remove the dependency.

**Closed** 2021-01-22 11:01 UTC

**Comment by Axieum** [comment] 2021-01-22 11:05
Hi, thanks for the quick reply!

I must add, however, that installing `pytest-runner` beforehand does not actually work. It will successfully download and install `pytest-runner`, but it still attempts to install it again from https://pypi.org/simple when it gets to the `cairocffi` dependency.

**Comment by Axieum** [comment] 2021-01-22 11:07
I know this isn't much information for you to go off, but I think it might be something to do with using an internally hosted PyPi repository?

**Comment by liZe** [comment] 2021-01-22 11:11
> I know this isn't much information for you to go off, but I think it might be something to do with using an internally hosted PyPi repository?

Well, I have no idea 😒.

As you already have your own PyPI, the easiest solution may be to remove `pytest-runner` from `setup.cfg` and build your own CairoCFFI package.
