### ISSUE TITLE
OSError: [Errno cairo returned CAIRO_STATUS_WRITE_ERROR: b'error while writing to output stream'] 11

### ISSUE THREAD

**Issue by brendabell** [Kozea/cairocffi#143] opened 2019-12-26 17:41 UTC
Python 3.7.4
CairoSVG 2.4.2
Mac OS X 10.14.6

Input file: https://gist.github.com/brendabell/408c12703d92868ed73bcdf04cf92ec7

Note that I did include absolute height, width and viewBox. My code is as follows:

```
result = generator.generate()
text_file = open("{}.svg".format(machine), "w")
text_file.write(result)
text_file.close()
png_file = open("{}.png".format(machine), "w")
cairosvg.svg2png(bytestring=result,write_to=png_file)
png_file.close()
```

The generated SVG file seems to be perfect. I started getting the error after the following upgrades:

Python 2.7.16 -> 3.7.4
CairoSVG 1.0.22 -> 2.4.2

**Comment by liZe** [comment] 2019-12-26 18:00
It works for me. This error happens when you cannot write to your destination file, you should check the rights set on your destination folder (and your destination file if it already exists).

**Comment by brendabell** [comment] 2019-12-26 19:58
> It works for me. This error happens when you cannot write to your destination file, you should check the rights set on your destination folder (and your destination file if it already exists).

I've confirmed the destination file does not exist. I also know it's not a permissions issue because my script is able to first create the SVG. It also creates the PNG, but the cairo write fails and I'm left with a zero-byte file.

Here's my `pip freeze` output. Can you verify whether you're using the same or different versions of something?

```cairocffi==1.1.0
CairoSVG==2.4.2
certifi==2019.11.28
cffi==1.13.2
cssselect2==0.2.2
defusedxml==0.6.0
Pillow==6.2.1
pipenv==2018.11.26
pycparser==2.19
pyparsing==2.4.6
svgwrite==1.3.1
tinycss2==1.0.2
virtualenv==16.7.9
virtualenv-clone==0.5.3
webencodings==0.5.1```

**Comment by brendabell** [comment] 2019-12-26 20:02
> It works for me. This error happens when you cannot write to your destination file, you should check the rights set on your destination folder (and your destination file if it already exists).

I just found a work-around. Instead of this:

```cairosvg.svg2png(file_obj=text_file,write_to=png_file)
```

I now have this which works:

```png_content = cairosvg.svg2png(file_obj=text_file)
png_file.write(png_content)
```

I think this is further evidence that it's not a permissions problem.

**Comment by liZe** [comment] 2019-12-26 21:36
Well… It may be related to #105 / #106, do you use a hardened system?

**Comment by L3o-pold** [comment] 2020-01-09 16:47
With this kind of code it fails on a python3.7 docker image

```python
png_content = cairosvg.svg2png(url="http://leopez.ch/glyphicons-halflings-regular.svg", dpi=96)
tmp_png.name.write(png_content)
```

```bash
  File "/usr/local/lib/python3.7/site-packages/cairosvg/__init__.py", line 70, in svg2png


    output_height=output_height)


  File "/usr/local/lib/python3.7/site-packages/cairosvg/surface.py", line 149, in convert


    instance.finish()


  File "/usr/local/lib/python3.7/site-packages/cairosvg/surface.py", line 499, in finish


    self.cairo.write_to_png(self.output)


  File "/usr/local/lib/python3.7/site-packages/cairocffi/surfaces.py", line 648, in write_to_png


    self._pointer, write_func, ffi.NULL))


  File "/usr/local/lib/python3.7/site-packages/cairocffi/__init__.py", line 88, in _check_status


    raise exception(message, status)


OSError: [Errno cairo returned CAIRO_STATUS_WRITE_ERROR: b'error while writing to output stream'] 11
```

**Comment by liZe** [comment] 2020-01-09 17:20
@L3o-pold Do you use a hardened system?

**Comment by L3o-pold** [comment] 2020-01-09 17:22
@liZe what do you mean by hardened?

**Comment by liZe** [comment] 2020-01-09 17:27
> @liZe what do you mean by hardened?

For example using [SELinux](https://fr.wikipedia.org/wiki/SELinux).

**Comment by L3o-pold** [comment] 2020-01-09 17:29
@liZe nop I use https://hub.docker.com/layers/python/library/python/3.7.6-stretch/images/sha256-45a5c2336da3d510b38481f968554e531f21831dbe7438e1f957127b1bc413be as base image

**Comment by brendabell** [comment] 2020-01-21 02:01
> Well… It may be related to #105 / #106, do you use a hardened system?

Unless Apple has done something really weird I don't know about in OS X 10.14.6, no.

**Comment by liZe** [comment] 2020-01-21 08:51
@L3o-pold Your problem is different from @brendabell’s one: you have to set a size in your SVG file (see #49). We should check that and raise an explicit error.

**Comment by L3o-pold** [comment] 2020-01-21 10:05
Thanks for the answer. I have not the hand on the files.

**Comment by liZe** [comment] 2020-01-21 10:50
> Thanks for the answer. I have not the hand on the files.

http://leopez.ch/glyphicons-halflings-regular.svg is an SVG font, that’s why it has no size. It can’t be rendered by a SVG renderer (you can try to open it in your browser).

**Comment by L3o-pold** [comment] 2020-01-21 10:51
@liZe yes I agree, maybe we should have a more adapted error message.

**Comment by liZe** [comment] 2020-01-23 09:56
> Unless Apple has done something really weird I don't know about in OS X 10.14.6, no.

I didn’t know, but macOS is also impacted by this problem, according to the [cffi documentation](https://cffi.readthedocs.io/en/latest/using.html?highlight=callback#callbacks-old-style). This bug is for sure a duplicate of #106, I’ll change its title to include macOS systems.

> @liZe yes I agree, maybe we should have a more adapted error message.

Done in 1f11100.

**Closed by liZe** 2020-01-23 09:56 UTC

**Comment by shibababa** [comment] 2021-01-28 10:19
Code mistake
×png_file = open("{}.png".format(machine), "w")
○png_file = open("{}.png".format(machine), "wb")
