### ISSUE TITLE
binary whl packages not provided on pypi

### ISSUE THREAD

**Issue by Tcll** [Kozea/cairocffi#189] opened 2021-05-13 13:06 UTC
I was looking to download a portable binary for universal linux py34 or py37 from pypi, but it appears you haven't pre-built any such packages:
https://pypi.org/project/cairocffi/#files

as such I can't use the portable program I'm trying to use with preferred portable interpreters.

**Comment by liZe** [comment] 2021-05-16 10:41
Hello!

Thanks for the report. This is a duplicate of #141.

**Closed by liZe** 2021-05-16 10:41 UTC
