### ISSUE TITLE
Unsatisfiable versions in conda

### ISSUE THREAD

**Issue by galpsten** [Kozea/cairocffi#138] opened 2019-09-06 11:49 UTC
Hi

I'm using the library Weasyprint, this being a dependency. I think the release yesterday might have broken something.

I am running python in a miniconda environment. My relevant configuration looks like this

```
name: XYZ
channels:
   - conda-forge
   - defaults
dependencies:
   # Basic
   - python
   - pip
   - conda

   # Genearate html to PDF
   - weasyprint
   - cairo >= 1.15.4 # 2D graphics library, version required by Weasyprint
```

Weasyprint request recent cairo versions. This worked until today, but I got this error today:

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cairo[version='>1.15.4']
  - weasyprint -> cairocffi[version='>=0.9.0'] -> cairo[version='1.14.*,>=1.14.12,<2.0a0']
```
I had initial issues with getting the versions to work out, but thought it might be good to flag for the issue in the meanwhile.

**Comment by liZe** [comment] 2019-09-06 13:54
Thanks for reporting!

The bug is in the cairocffi recipe: cairocffi doesn't only work with cairo 1.14.x versions, it works with more recent versions too.

You should open an issue [in their github repository](https://github.com/conda-forge/cairocffi-feedstock). You can also remove the patch, as it's not needed anymore (that's why PR for version 1.1.0 fails).

I'm closing this issue and WeasyPrint's one, as we now know that the issue is in the recipe.

**Closed by liZe** 2019-09-06 13:54 UTC

**Comment by galpsten** [comment] 2019-09-06 14:37
It may have been another issue. Closing for now
