### ISSUE TITLE
Fixing cairocffi[xcb] installation issues once for all

### ISSUE THREAD

**Issue by ramnes** [Kozea/cairocffi#214] opened 2023-06-01 10:05 UTC
Hey there, thanks for the awesome library and hard work throughout the years. :)

[Qtile](https://github.com/qtile/qtile), which depends on cairocffi + xcffib, always has been tricky to install: https://github.com/qtile/qtile/issues/994#issuecomment-497984551

It's getting much harder now that pip introduced builds isolation: https://github.com/qtile/qtile/pull/4285

On this 2020 thread, a pip developer suggested that we split the code so that pip can get the dependencies right: https://github.com/pypa/pipenv/issues/4482#issuecomment-706572894

From what I understand, it looks like it would solve once for all most installation problems related to cairocffi + xcffib. Would you be open to such a change?

**Comment by liZe** [comment] 2023-06-01 13:25
> From what I understand, it looks like it would solve once for all most installation problems related to cairocffi + xcffib. Would you be open to such a change?

That’s among the solutions I’ve been thinking of. It could possibly work, but having two different packages to maintain could add more work, and I’m not sure that we could keep the same API.

Maybe we can find a better solution. I’ve already tried different hacks (see #212). Getting [this issue](https://foss.heptapod.net/pypy/cffi/-/issues/441) fixed could also help, but that may not even be enough.

I’ve had another idea yesterday. Instead of generating files during the installation step, it’s probably possible to generate the same data at runtime. It’s less efficient, but if it only lasts a few milliseconds I think that nobody would care. Moreover, we could safely distribute wheels. And the xcb support would only depend on the xcffib lib being installed at runtime, avoiding errors like #190 or #100.

**Comment by ramnes** [comment] 2023-06-01 19:16
I quite like the runtime idea but doesn't that seems hacky to you in comparison to a cairocffi-xcb package?

@tych0 your input would be valuable here I guess

**Comment by tych0** [comment] 2023-06-01 19:21
I think the runtime idea makes it less likely we'll break the API, so that seems good.

Another crazy idea (or maybe this is the same): can we always build cairocffi with xcb/xcffib support, and then do some dlopen() magic when someone actually tries to use XCBSurface or whatever? That way the stock module import would work on systems that don't have/need/support xcb, but the stuff would be there for people who wanted to use it. Maybe we'd need support from cffi for this somehow.

**Comment by tych0** [comment] 2023-06-01 19:30
Another hack could be: generate two ffis, one with the xcb symbols and one without, and decide which to use at library import time based on some dlsym() hackery whackery.

**Comment by ramnes** [comment] 2023-06-01 20:17
> Another crazy idea (or maybe this is the same): can we always build cairocffi with xcb/xcffib support, and then do some dlopen() magic when someone actually tries to use XCBSurface or whatever?

I don't think we can force users to have X installed to build cairocffi, but (!) can't we just build and distribute wheels with xcb support by default? cairocffi and xcffib are both source-only on PyPI at the moment.

**Comment by liZe** [comment] 2023-06-01 21:32
> I don't think we can force users to have X installed to build cairocffi, but (!) can't we just build and distribute wheels with xcb support by default for Linux wheels?

The problem we have is that "normal" wheels may depend on Python version, OS, 32/64-bits… but we have one more thing we depend on: the version of Cairo. If we want to build wheels, in addition to setting CI to to automatically build and distribute them, we also have to embed a pre-compiled version of Cairo. That’s not impossible, but that’s another mess we probably don’t want to handle: Cairo devs release "beta" versions that fix some bugs and open other ones, and their very slow release frequency makes users want to use a specific version more than another depending on their needs. We’ve already spent countless days (weeks? months?) handling various problems on WeasyPrint, and that’s actually one of the reasons why we preferred to create our own PDF generation library than to continue to use Cairo.

(It doesn’t mean at all that Cairo is a bad tool, we really love it 💜. But we now think that it’s more adapted for GUI interfaces than for drawing libraries.)

So… I’d like to avoid this solution 😅️.

The solution I have in mind is to use [in-line](https://cffi.readthedocs.io/en/latest/overview.html#simple-example-abi-level-in-line) instead of [out-of-line](https://cffi.readthedocs.io/en/latest/overview.html#out-of-line-abi-level-1) ABI mode to reach the Cairo library. We’ve used this solution for WeasyPrint, it works well and avoids static generation.

The main problem of this solution is the module import speed. On my computer, import time is ~150ms longer. Other real-life tests would be useful to check different use cases, but this trade-off would be OK for me.

There are many advantages too:
- we don’t have to install xcffib before cairocffi,
- we can distribute wheels, and actually the same wheel everywhere,
- we don’t rely on cffi’s setuptools hook,
- we have less code to maintain.

And… This solution is not only in my mind anymore, it’s also on the in-line branch 😄. Tests are welcome!

**Comment by tych0** [comment] 2023-06-01 23:13
I tried it and got:
```
2023-06-01 17:05:24,399 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 205, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 230, in async_loop
    self.load_config(initial=True)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 143, in load_config
    self._process_screens(reloading=not initial)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 382, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/config.py", line 481, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/bar.py", line 283, in _configure
    self.drawer.clear(self.background)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 180, in clear
    self._check_xcb()
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 127, in _check_xcb
    self._xcb_surface = self._create_xcb_surface()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 92, in _create_xcb_surface
    surface = cairocffi.XCBSurface(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: initializer for ctype 'xcb_connection_t *' appears indeed to be 'xcb_connection_t *', but the types are different (check that you are not e.g. mixing up different ffi instances)
```

I'm not sure I understand what it means, though. it looks to me like the code is correctly including xcffib's ffi. Is there something else we can export to fix it up I wonder?

**Comment by tych0** [comment] 2023-06-01 23:17
Or maybe I need to do the same transformation on xcffib? It looks like it is also compiling vs. using the inline ABI mode.

**Comment by ramnes** [comment] 2023-06-01 23:48
The error seems related to what they say in the cffi docs linked just above about the inline ABI mode: 

> This example does not call any C compiler. It works in the so-called ABI mode, which means that **it will crash if you call some function or access some fields of a structure that was slightly misdeclared in the cdef().**

**Comment by ramnes** [comment] 2023-06-02 00:09
Any chance that something like `ffi.cast("struct _cairo *", cairo_t)` works? `cairo_t` is just a typedef for `struct _cairo`

**Comment by tych0** [comment] 2023-06-02 01:31
Probably, but the [docs also say it should work](https://cffi.readthedocs.io/en/latest/cdef.html#ffi-ffibuilder-include-combining-multiple-cffi-interfaces), at least by my read:

"ffi/ffibuilder.include(other_ffi): includes the typedefs, structs, unions, enums and constants defined in another FFI instance."

I guess maybe cffi doesn't actually expand typedefs, and is reliant on the C compiler to do that? If so, seems like this change might break some people...

**Comment by tych0** [comment] 2023-06-02 03:03
Yeah, that works, and qtile boots for me with https://github.com/qtile/qtile/commit/3fa30704febf66b87c1ec8b1bfc3c63a3362c464

**Comment by tych0** [comment] 2023-06-02 03:27
idk, I tried reproducing with:

```
~ cat tester.py
#!/usr/bin/python3

import cffi

ffi1 = cffi.FFI()

ffi1.cdef("""
typedef struct _opaque opaque_t;

opaque_t *create_opaque(void);
""")
lib1 = ffi1.dlopen("./tester.so")

ffi2 = cffi.FFI()
ffi2.include(ffi1)

ffi2.cdef("""
void consume_opaque(opaque_t *);
""")
lib2 = ffi2.dlopen("./tester.so")

op = lib1.create_opaque()
lib2.consume_opaque(op)
~ cat tester.c
#include <stddef.h>

typedef struct _opaque opaque_t;

opaque_t *create_opaque(void)
{
	return NULL;
}

void consume_opaque(opaque_t *) { }
```

but this works fine, so I think it Should Work, and I must be missing some install nuance on my system?

**Comment by ramnes** [comment] 2023-06-02 06:20
I think a cast doesn't make any harm :)

**Comment by liZe** [comment] 2023-06-02 07:23
> Ok, I got a bit further with:
> 
> [tych0/xcffib@d182364](https://github.com/tych0/xcffib/commit/d18236470794f11305187f79d04661e1562710e0)
> 
> and
> 
> [5764f46](https://github.com/Kozea/cairocffi/commit/5764f46b317ceb4193769f444243897ff782739f)

I’ve committed and pushed this change, with a couple of other fixes.

**Comment by tych0** [comment] 2023-06-02 14:01
> I think a cast doesn't make any harm :)

It's more that there's some risk the change breaks things. I admit I don't understand all the details of cffi, but I wouldn't have expected to need to make changes to user code here.

**Comment by tych0** [comment] 2023-06-02 14:03
> I’ve committed and pushed this change, with a couple of other fixes.

I'll try and fix the xcffib branch up and do a release with it soon-ish, so you can add it as a version constraint if you want to merge this to main. Thanks for looking into this.

**Comment by tych0** [comment] 2023-06-03 00:16
Ok, I just released xcffib 1.4.0, which has my xcffib patch above.

**Comment by liZe** [comment] 2023-06-04 22:57
CairoCFFI and CairoSVG tests pass, that’s good news! I’ll release a new version soon.

**Comment by ramnes** [comment] 2023-06-11 00:26
Qtile tests pass!

Well they pass but on commit 178deaf and not the later ones, because there's no wheel available and we don't have Flit installed.

That shouldn't be a problem after release though since this is giving us universal wheels.

Do you have any timeframe in mind for the release? :)

**Comment by liZe** [comment] 2023-06-11 08:10
> Qtile tests pass!
> 
> Well they pass but on commit [178deaf](https://github.com/Kozea/cairocffi/commit/178deaf80c0aece78cc84ff920d5076f3670137a) and not the later ones, because there's no wheel available and we don't have Flit installed.
> 
> That shouldn't be a problem after release though since this is giving us universal wheels.

Yes, that shouldn’t be a problem.

> Do you have any timeframe in mind for the release? :)

Probably Tuesday!

**Closed** 2023-06-12 07:59 UTC

**Comment by liZe** [comment] 2023-06-12 08:23
@ramnes CairoCFFI 1.6.0 has just been released.

**Comment by ramnes** [comment] 2023-06-12 08:59
Yeah I've seen it and started upgrading the branch on Qtile. Thank you very much!
