### ISSUE TITLE
VERSION instead of the verision number!

### ISSUE THREAD

**Issue by obiwankennedy** [Kozea/cairocffi#155] opened 2020-04-30 00:41 UTC
I try to install markdown2pdf and it requires cairocffi but pip install can't allow it:

> has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.

**Comment by liZe** [comment] 2020-04-30 07:52
Hello!

You need a more recent version of Setuptools (v39.2.0 I think).

**Comment by utkarshshah007** [comment] 2020-05-08 19:13
Hello! I'm seeing the same issue with setuptools v46.1.3 on Mac.

This issue also appears when I try to install cairocffi v1.1.0 directly:
```
$ pip install cairocffi==1.1.0
Collecting cairocffi==1.1.0
Requirement already satisfied: setuptools>=39.2.0 in ./env/lib/python3.6/site-packages (from cairocffi==1.1.0) (46.1.3)
Requirement already satisfied: cffi>=1.1.0 in ./env/lib/python3.6/site-packages (from cairocffi==1.1.0) (1.14.0)
Requirement already satisfied: pycparser in ./env/lib/python3.6/site-packages (from cffi>=1.1.0->cairocffi==1.1.0) (2.20)
ERROR: weasyprint 51 has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.
Installing collected packages: cairocffi
Successfully installed cairocffi-file-.cairocffi-VERSION
```

**Comment by liZe** [comment] 2020-05-08 19:31
Hello!

Could you try to launch `pip` with the `--no-cache-dir` option? I suppose that there’s something wrong with your cache.

**Comment by utkarshshah007** [comment] 2020-05-08 19:36
Thanks! That was it - seems like it was processing the old wheel

**Comment by liZe** [comment] 2020-05-08 19:41
> Thanks! That was it - seems like it was processing the old wheel

Cool!

Closing, as the original problem is definitely caused by an old version of Setuptools.

**Closed by liZe** 2020-05-08 19:41 UTC
